CREATE SEQUENCE seq_cityscape_user_id       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_adventure_id             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_lista_id                 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_review_id                START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_completed_adventure_id   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_abandoned_adventure_id   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_station_id               START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cityscape_user_h_id      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_adventure_status_h_id    START WITH 1 INCREMENT BY 1;
